[workspace]
members = [
    "synclipperd",
    "synclipper",
    "synclipper-proto",
]

[workspace.package]
authors = ["BppleMan"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
clipboard = "0.5.0"

prost = "0.11.9"
tonic = "0.9.2"
tokio = { version = "1.32.0", features = ["full"] }
async-stream = "0.3.5"
tokio-stream = "0.1.14"
log = "0.4.20"
color-eyre = "0.6.2"
